# ``conda env create --file environment.yml``
# or
# ``conda env create --name <myEnvName> --file environment.yml``

name: advanced-git
dependencies:
  - matplotlib
  - numpy
  - pandas
  - python=3.7
