# ``conda env create --file environment.yml``
# or
# ``conda env create --name <myEnvName> --file environment.yml``

name: advanced-git
dependencies:
  - matplotlib
  - flake8
  - numpy
  - pandas
  - pytest
  - python=3.9
